spring:
  datasource:
    url: jdbc:oracle:@oracle.fiap.com.br:1521:ORCL
    username: RM551456
    password: 150404
  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false
    show-sql: true
